export const USER_LOGOUT = 'USER_LOGOUT_ACTION'
export const USER_REPLACE = 'USER_REPLACE_ACTION'
export const USER_WITH_GOOGLE = 'USER_WITH_GOOGLE'

export const USER_LOGIN = USER_REPLACE
export const USER_REGISTER = USER_REPLACE
export const USER_UPDATE = USER_REPLACE
