FROM node:18-bullseye-slim as prune
ARG Package_name

WORKDIR /app
COPY . .
RUN npx turbo prune --scope ${Package_name} --docker

# npm install & build
FROM node:18-bullseye-slim
ARG Package_name


WORKDIR /app
COPY --from=prune /app/out/json/ .
COPY --from=prune /app/out/package-lock.json ./package-lock.json
RUN npm install
COPY --from=prune /app/out/full/ .

RUN npx turbo build --filter ${Package_name}

# final image
FROM gcr.io/distroless/nodejs:18
ARG Package_name
ARG Package_dir=apps/$Package_name

WORKDIR /app
COPY --from=1 /app/$Package_dir/dist .
USER nonroot

EXPOSE 3000
CMD ["index.bundle.js"]