FROM node:18-buster-slim as prune
ARG Package_name

WORKDIR /app
RUN npm i -g turbo

COPY . .
RUN turbo prune --scope ${Package_name} --docker

# npm install & build
FROM node:18-buster-slim
ARG Package_name

WORKDIR /app
COPY --from=prune /app/out/json/ .
COPY --from=prune /app/out/package-lock.json ./package-lock.json
RUN npm install
COPY --from=prune /app/out/full/ .

RUN npm run build:base -w ${Package_name}

# final image
FROM node:18-buster-slim
ARG Package_name
ARG Package_location="apps"
ARG Package_dir=$Package_location/$Package_name

WORKDIR /app
COPY --from=1 /app/$Package_dir/dist .

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs

EXPOSE 3000
CMD ["node", "index.bundle.js"]