const color = require("color");

const startingWith = [
  "f8cd92",
  "6074ff",
  "ec7194",
  "4cbfbc",
  "d38ead",
  "d289f5",
  "1ca2ef",
  "a178fa",
];

const each = (cb) => color.rgb(eArr.map(cb)).hex();

const colorsObj = startingWith.map((e) => {
  e = color(`#${e}`);
  eArr = e.rgb().array();

  return {
    tint80: each((chnl) => chnl + (255 - chnl) * 0.8),
    tint40: each((chnl) => chnl + (255 - chnl) * 0.4),
    tint20: each((chnl) => chnl + (255 - chnl) * 0.2),
    shade30: each((chnl) => chnl * 0.7),
    shade60: each((chnl) => chnl * 0.4),
    base: e.hex(),
    className: `category-color-${e.hex().substring(1)}`,
  };
});

const iconsObj = [
  "Star Icon",
  "School Icon",
  "Sports Esports Icon",
  "Self Improvement Icon",
  "Cake Icon",
  "Sports Soccer Icon",
  "Hiking Icon",
  "Connect Without Contact Icon",
  "Luggage Icon",
  "Sports Basketball Icon",
  "King Bed Icon",
  "Sports Tennis Icon",
  "Outdoor Grill Icon",
  "Surfing Icon",
  "Sports Motorsports Icon",
  "Sports Baseball Icon",
  "Sports Handball Icon",
  "Sports Volleyball Icon",
  "Kayaking Icon",
  "Sports Football Icon",
  "Skateboarding Icon",
  "Interests Icon",
  "Coffee Icon",
  "Shower Icon",
  "Chair Icon",
  "House Icon",
  "Casino Icon",
  "Flight Icon",
  "Restaurant Icon",
  "Handyman Icon",
  "Local Mall Icon",
  "Local Library Icon",
  "Celebration Icon",
  "Lunch Dining Icon",
  "Local Cafe Icon",
  "Local Atm Icon",
  "Local Grocery Store Icon",
  "Local Florist Icon",
  "Local Gas Station Icon",
  "Train Icon",
  "Two Wheeler Icon",
  "Pedal Bike Icon",
  "Directions Boat Icon",
  "Local Pizza Icon",
  "Local See Icon",
  "Phone Iphone Icon",
  "Desktop Windows Icon",
  "Laptop Icon",
  "Tv Icon",
  "Headphones Icon",
  "Speaker Icon",
  "Keyboard Alt Icon",
  "Nightlight Icon",
  "Sentiment Satisfied Alt Icon",
  "Vpn Key Icon",
  "Play Circle Icon",
  "Movie Icon",
  "Error Icon",
  "Add Alert Icon",
  "Check Circle Icon",
  "Favorite Icon",
  "Event Icon",
  "Account Balance Icon",
  "Work Icon",
  "Savings Icon",
  "Shopping Basket Icon",
  "Stars Icon",
  "Extension Icon",
  "G Translate Icon",
  "Outlet Icon",
];

module.exports = { colorsObj, iconsObj };
