// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Jwt_ { id: string, email: string, user_id: string, exp: string, iat: string, }