// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MyErrors = { "EmailAlreadyExists": string } | "AssociatedEntriesExist" | "EmailOrPasswordIncorrect" | { "ValidationError": string } | "NotFound" | "ExpiredBearerToken" | "InternalError" | { "BadRequest": string };