// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserRestResponse { id: string, email: string, display_name: string | null, avatar: string | null, providers: string, created_at: number, updated_at: number, }