[lib]
proc-macro = true

[package]
name = "http_error_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.33"
quote = "1.0.33"
syn = "2.0.29"
actix-web = "4.3.1"
