version: "3.8"
services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..

    env_file:
      - .env.dev

    volumes:
      - ..:/repo:cached
      - /repo/node_modules # unmaped volume; belong to Dockerfile
      - /repo/target # unmaped volume; belong to Dockerfile

    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432

volumes:
  postgres-data:
