/// <reference types="node" />
import { compile } from 'json-schema-to-typescript'
import * as Schemas from '../json-schema'
import { writeFileSync } from 'fs'

async function main(obj: object, src: string) {
  const schemas = Object.entries(obj).map(([name, schema]) => {
    return compile(
      {
        ...schema,
        $id: schema.$id.replace(/^\//, '').replace(/\//g, '_'),
      },
      name,
      {
        bannerComment: '',
      },
    ) as Promise<string>
  })

  const file = await Promise.all(schemas).then(ts => {
    return `
/* eslint-disable */
// This file was automatically generated by json-schema-to-typescript.
// DO NOT MODIFY IT BY HAND. Instead, modify \`src/json-schema/${src}.ts\`,
// and run json-schema-to-typescript to regenerate this file.
${ts.join('\n\n')}
`
  })

  writeFileSync(`./dist/ts/${src}.ts`, file, {
    encoding: 'utf-8',
  })

  console.log('build-ts: file written ./dist/ts/' + src + '.ts')
}

Object.entries(Schemas).forEach(([name, schema]) => {
  if (name === 'default') {
    return
  }
  main(schema, name)
})
