/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the file pkgs\ui\types\SB.d.ts
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
import { StoryObj } from '@storybook/react'
import { ExpParameter, ExpTags, ExpDecorator } from 'ui/types/SB'

declare global {
  namespace SB {
    export type Decorator = ExpDecorator

    export type Meta<C extends (P: any) => JSX.Element> = Omit<
      ExpTags<C>,
      'parameters' | 'tags'
    > & {
      parameters?: ExpParameter
      tags?: _Tags[]
    }

    export type Story<C extends (P: any) => JSX.Element> = Omit<
      StoryObj<C>,
      'parameters' | 'tags'
    > & {
      parameters?: ExpParameter
      tags?: _Tags[]
    }
  }
}
