export { Adjustments } from 'tabler-icons-react'
export { Plus } from 'tabler-icons-react'
export { Category2 } from 'tabler-icons-react'
export { Blur } from 'tabler-icons-react'
export { Circle } from 'tabler-icons-react'

/**
 * got this list from https://tabler-icons-react.vercel.app/
 * using this script 
```js
const targetNode = document.querySelector('.card-title');
const allIcon = []

const config = { attributes: true, childList: true, subtree: true };

const callback = (mutationList, observer) => {
    const value = targetNode.innerHTML
    if(!allIcon.some((e) => e===value)) allIcon.push(value)
    console.log(allIcon)
  
};

const observer = new MutationObserver(callback);

observer.observe(targetNode, config);
```
 * */
export { World } from 'tabler-icons-react'
export { Wind } from 'tabler-icons-react'
export { Wallet } from 'tabler-icons-react'
export { Walk } from 'tabler-icons-react'
export { Video } from 'tabler-icons-react'
export { Users } from 'tabler-icons-react'
export { Ufo } from 'tabler-icons-react'
export { Truck } from 'tabler-icons-react'
export { TruckLoading } from 'tabler-icons-react'
export { Train } from 'tabler-icons-react'
export { ToolsKitchen } from 'tabler-icons-react'
export { Tool } from 'tabler-icons-react'
export { Tie } from 'tabler-icons-react'
export { Tag } from 'tabler-icons-react'
export { Sun } from 'tabler-icons-react'
export { Soup } from 'tabler-icons-react'
export { Sofa } from 'tabler-icons-react'
export { Sock } from 'tabler-icons-react'
export { ShoppingCart } from 'tabler-icons-react'
export { Ship } from 'tabler-icons-react'
export { Shirt } from 'tabler-icons-react'
export { Run } from 'tabler-icons-react'
export { Sailboat } from 'tabler-icons-react'
export { Plant } from 'tabler-icons-react'
export { PlaneTilt } from 'tabler-icons-react'
export { Pizza } from 'tabler-icons-react'
export { Pig } from 'tabler-icons-react'
export { Phone } from 'tabler-icons-react'
export { Palette } from 'tabler-icons-react'
export { Motorbike } from 'tabler-icons-react'
export { MoodHappy } from 'tabler-icons-react'
export { MoodBoy } from 'tabler-icons-react'
export { MoodCrazyHappy } from 'tabler-icons-react'
export { MoodSad } from 'tabler-icons-react'
export { Meat } from 'tabler-icons-react'
export { LetterZ } from 'tabler-icons-react'
export { LetterY } from 'tabler-icons-react'
export { LetterU } from 'tabler-icons-react'
export { LetterV } from 'tabler-icons-react'
export { LetterW } from 'tabler-icons-react'
export { LetterX } from 'tabler-icons-react'
export { LetterT } from 'tabler-icons-react'
export { LetterS } from 'tabler-icons-react'
export { LetterR } from 'tabler-icons-react'
export { LetterN } from 'tabler-icons-react'
export { LetterO } from 'tabler-icons-react'
export { LetterP } from 'tabler-icons-react'
export { LetterQ } from 'tabler-icons-react'
export { LetterM } from 'tabler-icons-react'
export { LetterL } from 'tabler-icons-react'
export { LetterK } from 'tabler-icons-react'
export { LetterJ } from 'tabler-icons-react'
export { LetterF } from 'tabler-icons-react'
export { LetterG } from 'tabler-icons-react'
export { LetterH } from 'tabler-icons-react'
export { LetterI } from 'tabler-icons-react'
export { LetterE } from 'tabler-icons-react'
export { LetterD } from 'tabler-icons-react'
export { LetterC } from 'tabler-icons-react'
export { LetterB } from 'tabler-icons-react'
export { LetterA } from 'tabler-icons-react'
export { Heart } from 'tabler-icons-react'
export { Headset } from 'tabler-icons-react'
export { GlassFull } from 'tabler-icons-react'
export { Friends } from 'tabler-icons-react'
export { Flag } from 'tabler-icons-react'
// export { Circle0 } from 'tabler-icons-react'
// export { Circle1 } from 'tabler-icons-react'
// export { Circle2 } from 'tabler-icons-react'
// export { Circle3 } from 'tabler-icons-react'
// export { Circle7 } from 'tabler-icons-react'
// export { Circle6 } from 'tabler-icons-react'
// export { Circle5 } from 'tabler-icons-react'
// export { Circle4 } from 'tabler-icons-react'
// export { Circle8 } from 'tabler-icons-react'
// export { Circle9 } from 'tabler-icons-react'
export { CircleCheck } from 'tabler-icons-react'
export { ChartBar } from 'tabler-icons-react'
export { Cash } from 'tabler-icons-react'
export { CashOff } from 'tabler-icons-react'
export { Car } from 'tabler-icons-react'
export { CaretUp } from 'tabler-icons-react'
export { CaretDown } from 'tabler-icons-react'
export { CaretLeft } from 'tabler-icons-react'
export { CaretRight } from 'tabler-icons-react'
export { BuildingBank } from 'tabler-icons-react'
export { Bone } from 'tabler-icons-react'
export { Beach } from 'tabler-icons-react'
export { Beer } from 'tabler-icons-react'
export { Bed } from 'tabler-icons-react'
export { Barbell } from 'tabler-icons-react'
export { BallFootball } from 'tabler-icons-react'
export { BallAmericanFootball } from 'tabler-icons-react'
export { BallBowling } from 'tabler-icons-react'
